{{- if and .Values.backend.enabled .Values.backend.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "aimvision.backend.fullname" . }}
  labels:
    {{- include "aimvision.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  annotations:
    {{- with .Values.backend.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with (include "aimvision.annotations" .) }}
    {{- . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.backend.ingress.className }}
  ingressClassName: {{ .Values.backend.ingress.className }}
  {{- end }}
  {{- if .Values.backend.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ include "aimvision.backend.host" . | quote }}
      secretName: {{ .Values.backend.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ include "aimvision.backend.host" . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "aimvision.backend.fullname" . }}
                port:
                  number: {{ .Values.backend.service.port }}
{{- end }}
