{{- if .Values.minio.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aimvision.minio.fullname" . }}
  labels:
    {{- include "aimvision.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: {{ .Values.minio.service.type }}
  ports:
    - name: api
      port: {{ .Values.minio.service.port }}
      targetPort: api
      protocol: TCP
    - name: console
      port: {{ .Values.minio.service.consolePort }}
      targetPort: console
      protocol: TCP
  selector:
    {{- include "aimvision.minio.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aimvision.minio.fullname" . }}-headless
  labels:
    {{- include "aimvision.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: api
      port: {{ .Values.minio.service.port }}
      targetPort: api
      protocol: TCP
  selector:
    {{- include "aimvision.minio.selectorLabels" . | nindent 4 }}
{{- end }}
