{{- if .Values.temporal.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aimvision.temporal.fullname" . }}
  labels:
    {{- include "aimvision.labels" . | nindent 4 }}
    app.kubernetes.io/component: temporal
spec:
  type: {{ .Values.temporal.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.temporal.service.port }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "aimvision.temporal.selectorLabels" . | nindent 4 }}
{{- end }}
