#!/usr/bin/env python3
"""Refresh the auto-generated section of CLAUDE.md.

Run manually with `python3 scripts/update_context.py`, or let the
`.github/workflows/update-context.yml` workflow run it on every push.
The script only rewrites the block between the AUTO:BEGIN/AUTO:END
markers, so any hand-written context above or below is preserved.
"""
from __future__ import annotations

import datetime as _dt
import pathlib
import re
import subprocess
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTEXT = REPO_ROOT / "CLAUDE.md"
BEGIN = "<!-- AUTO:BEGIN -->"
END = "<!-- AUTO:END -->"
MAX_FILES = 80


def sh(*args: str) -> str:
    try:
        return subprocess.check_output(args, cwd=REPO_ROOT, text=True).strip()
    except subprocess.CalledProcessError:
        return ""


def main() -> int:
    if not CONTEXT.exists():
        print(f"update_context: {CONTEXT} missing", file=sys.stderr)
        return 0

    last_updated = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    branch = sh("git", "rev-parse", "--abbrev-ref", "HEAD") or "unknown"
    commits = sh("git", "rev-list", "--count", "HEAD") or "0"
    remote = sh("git", "config", "--get", "remote.origin.url") or "no remote configured"

    log = sh("git", "log", "-n", "10", "--pretty=format:- %h %s (%an, %ar)")
    recent = log if log else "- (no commits yet)"

    files = [
        f for f in sh("git", "ls-files").splitlines()
        if not f.startswith(".claude/")
    ]
    tracked_count = len(files)
    tree = "\n".join(f"- {f}" for f in files[:MAX_FILES]) or "- (no tracked files yet)"

    block = (
        f"{BEGIN}\n"
        "<!-- Regenerated by scripts/update_context.py via GitHub Actions on every push. Do not edit by hand. -->\n\n"
        f"**Last updated:** {last_updated}\n"
        f"**Branch:** `{branch}` · **Commits:** {commits} · **Tracked files:** {tracked_count}\n"
        f"**Remote:** {remote}\n\n"
        "### Recent commits\n"
        f"{recent}\n\n"
        f"### Tracked files (first {MAX_FILES})\n"
        f"{tree}\n"
        f"{END}"
    )

    text = CONTEXT.read_text()
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if pattern.search(text):
        text = pattern.sub(block, text)
    else:
        text = text.rstrip() + "\n\n" + block + "\n"
    CONTEXT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
